name: Build .NET SDK

run-name: "Build .NET SDK : ${{ inputs.branch }}"

on:
  workflow_dispatch:
    inputs:
      fork:
        description: 'dotnet VMR fork name'
        required: true
        type: string
        default: dotnet
      branch:
        description: 'dotnet VMR branch name'
        required: true
        type: string
        default: main
      branding:
        description: 'SDK branding'
        required: true
        type: choice
        options:
          - unstable
          - preview
          - release
        default: preview
      release:
        description: 'publish release'
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux
            libc: glibc
            docker_tag: azurelinux-3.0-net10.0-cross-riscv64
          - name: linux-musl
            libc: musl
            docker_tag: azurelinux-3.0-net10.0-cross-riscv64-musl

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Maximize build space
      uses: AdityaGarg8/remove-unwanted-software@v4.1
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-cached-tools: 'true'

    - name: Clone repository
      run: |
        git clone --single-branch --depth 1 -b ${{ inputs.branch }} https://github.com/${{ inputs.fork }}/dotnet

    - name: Build
      run: |
        major_version=$(echo "${{ inputs.branch }}" | sed -E 's/^v?([0-9]+)\..*/\1/')

        branding_arg=""
        if [[ "$major_version" =~ ^[0-9]+$ ]] && [ "$major_version" -ge 11 ]; then
          branding_arg="--branding ${{ inputs.branding }}"
        fi

        echo "Major version: $major_version"
        echo "Branding argument: $branding_arg"

        docker run --platform linux/amd64 --rm -v${{ github.workspace }}/dotnet:/dotnet -w /dotnet -e ROOTFS_DIR=/crossrootfs/riscv64 \
          mcr.microsoft.com/dotnet-buildtools/prereqs:${{ matrix.docker_tag }} \
            ./build.sh --clean-while-building --prep -sb --os ${{ matrix.name }} --rid ${{ matrix.name }}-riscv64 --arch riscv64 \
              $branding_arg -p:OfficialBuildId=$(date +%Y%m%d).99

    - name: List assets directory
      run: |
        find "${{ github.workspace }}/dotnet/artifacts"

    - name: Upload .NET
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-sdk-${{ matrix.name }}
        path: |
          ${{ github.workspace }}/dotnet/artifacts/assets/Release/Sdk/*/dotnet-sdk-*.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    if: always() && inputs.release

    permissions:
      contents: write

    steps:
    - name: Download artifacts
      if: needs.build.result == 'success'
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Make release (Success)
      if: needs.build.result == 'success'
      run: |
        sdk_paths=$(find "${{ github.workspace }}/artifacts" -name 'dotnet-sdk-*.tar.gz')

        artifacts=""
        tag_name=""

        for sdk_path in $sdk_paths; do
          sdk_filename=$(basename "$sdk_path")
          sdk_version=$(echo "$sdk_filename" | sed -E 's/dotnet-sdk-([^-]+(-[^-]+)*)-linux-.+\.tar\.gz/\1/')
          artifacts="$artifacts $sdk_path"
          tag_name="$sdk_version"
        done

        echo "tag_name: $tag_name"
        echo "artifacts: $artifacts"

        if [ "${{ inputs.branding }}" = "release" ]; then
          gh release create "$tag_name" $artifacts --repo "${{ github.repository }}" --target "${{ github.sha }}" --title "$tag_name" --notes "$tag_name"
        else
          gh release create "$tag_name" $artifacts --repo "${{ github.repository }}" --target "${{ github.sha }}" --title "$tag_name" --notes "$tag_name" --prerelease
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create failed tag
      if: needs.build.result == 'failure' && inputs.branch != 'main'
      run: |
        tag_name="${{ inputs.branch }}.${{ github.run_id }}.failed"
        echo "tag_name: $tag_name"

        gh api repos/${{ github.repository }}/git/refs -f ref="refs/tags/$tag_name" -f sha="${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
